/**
 * @fileoverview gRPC-Web generated client stub for kv
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: kv.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as kv_pb from './kv_pb'; // proto import: "kv.proto"


export class KeyValueClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPut = new grpcWeb.MethodDescriptor(
    '/kv.KeyValue/Put',
    grpcWeb.MethodType.UNARY,
    kv_pb.PutRequest,
    kv_pb.PutResponse,
    (request: kv_pb.PutRequest) => {
      return request.serializeBinary();
    },
    kv_pb.PutResponse.deserializeBinary
  );

  put(
    request: kv_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kv_pb.PutResponse>;

  put(
    request: kv_pb.PutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kv_pb.PutResponse) => void): grpcWeb.ClientReadableStream<kv_pb.PutResponse>;

  put(
    request: kv_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kv_pb.PutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kv.KeyValue/Put',
        request,
        metadata || {},
        this.methodDescriptorPut,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kv.KeyValue/Put',
    request,
    metadata || {},
    this.methodDescriptorPut);
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/kv.KeyValue/Get',
    grpcWeb.MethodType.UNARY,
    kv_pb.GetRequest,
    kv_pb.GetResponse,
    (request: kv_pb.GetRequest) => {
      return request.serializeBinary();
    },
    kv_pb.GetResponse.deserializeBinary
  );

  get(
    request: kv_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kv_pb.GetResponse>;

  get(
    request: kv_pb.GetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kv_pb.GetResponse) => void): grpcWeb.ClientReadableStream<kv_pb.GetResponse>;

  get(
    request: kv_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kv_pb.GetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kv.KeyValue/Get',
        request,
        metadata || {},
        this.methodDescriptorGet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kv.KeyValue/Get',
    request,
    metadata || {},
    this.methodDescriptorGet);
  }

  methodDescriptorReplicate = new grpcWeb.MethodDescriptor(
    '/kv.KeyValue/Replicate',
    grpcWeb.MethodType.UNARY,
    kv_pb.PutRequest,
    kv_pb.PutResponse,
    (request: kv_pb.PutRequest) => {
      return request.serializeBinary();
    },
    kv_pb.PutResponse.deserializeBinary
  );

  replicate(
    request: kv_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kv_pb.PutResponse>;

  replicate(
    request: kv_pb.PutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kv_pb.PutResponse) => void): grpcWeb.ClientReadableStream<kv_pb.PutResponse>;

  replicate(
    request: kv_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kv_pb.PutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kv.KeyValue/Replicate',
        request,
        metadata || {},
        this.methodDescriptorReplicate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kv.KeyValue/Replicate',
    request,
    metadata || {},
    this.methodDescriptorReplicate);
  }

  methodDescriptorGetChunkHash = new grpcWeb.MethodDescriptor(
    '/kv.KeyValue/GetChunkHash',
    grpcWeb.MethodType.UNARY,
    kv_pb.ChunkRequest,
    kv_pb.ChunkHashResponse,
    (request: kv_pb.ChunkRequest) => {
      return request.serializeBinary();
    },
    kv_pb.ChunkHashResponse.deserializeBinary
  );

  getChunkHash(
    request: kv_pb.ChunkRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kv_pb.ChunkHashResponse>;

  getChunkHash(
    request: kv_pb.ChunkRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kv_pb.ChunkHashResponse) => void): grpcWeb.ClientReadableStream<kv_pb.ChunkHashResponse>;

  getChunkHash(
    request: kv_pb.ChunkRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kv_pb.ChunkHashResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kv.KeyValue/GetChunkHash',
        request,
        metadata || {},
        this.methodDescriptorGetChunkHash,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kv.KeyValue/GetChunkHash',
    request,
    metadata || {},
    this.methodDescriptorGetChunkHash);
  }

  methodDescriptorFetchRange = new grpcWeb.MethodDescriptor(
    '/kv.KeyValue/FetchRange',
    grpcWeb.MethodType.SERVER_STREAMING,
    kv_pb.RangeRequest,
    kv_pb.KeyValuePair,
    (request: kv_pb.RangeRequest) => {
      return request.serializeBinary();
    },
    kv_pb.KeyValuePair.deserializeBinary
  );

  fetchRange(
    request: kv_pb.RangeRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<kv_pb.KeyValuePair> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/kv.KeyValue/FetchRange',
      request,
      metadata || {},
      this.methodDescriptorFetchRange);
  }

}

