# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"=\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0bmodified_at\x18\x03 \x01(\x03\"*\n\x0bPutResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x0c\x43hunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\"!\n\x11\x43hunkHashResponse\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\" \n\x0cRangeRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\x32\xf5\x01\n\x08KeyValue\x12&\n\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12&\n\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x12,\n\tReplicate\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12\x37\n\x0cGetChunkHash\x12\x10.kv.ChunkRequest\x1a\x15.kv.ChunkHashResponse\x12\x32\n\nFetchRange\x12\x10.kv.RangeRequest\x1a\x10.kv.KeyValuePair0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=16
  _globals['_PUTREQUEST']._serialized_end=77
  _globals['_PUTRESPONSE']._serialized_start=79
  _globals['_PUTRESPONSE']._serialized_end=121
  _globals['_GETREQUEST']._serialized_start=123
  _globals['_GETREQUEST']._serialized_end=148
  _globals['_GETRESPONSE']._serialized_start=150
  _globals['_GETRESPONSE']._serialized_end=193
  _globals['_KEYVALUEPAIR']._serialized_start=195
  _globals['_KEYVALUEPAIR']._serialized_end=237
  _globals['_CHUNKREQUEST']._serialized_start=239
  _globals['_CHUNKREQUEST']._serialized_end=271
  _globals['_CHUNKHASHRESPONSE']._serialized_start=273
  _globals['_CHUNKHASHRESPONSE']._serialized_end=306
  _globals['_RANGEREQUEST']._serialized_start=308
  _globals['_RANGEREQUEST']._serialized_end=340
  _globals['_KEYVALUE']._serialized_start=343
  _globals['_KEYVALUE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
